### PR TITLE
Support deserializing to generic geometry type

### PR DESCRIPTION
**Pull request by shuternay**
This PR implements deserializing to geometry with generic coordinate type

### CODE REVIEW

**Comment by amandasaurus** [comment]
Doesn't the WKB standard/spec only allow `f64` data types? Sure this would make the code more generic, but at a cost of moving away from the standard (right?)

**Comment by shuternay** [comment]
Yes, WKB (as binary representation) uses `f64` data type, but this PR doesn't change it, it allows to convert f64-WKB to `Geometry<T>` (with possible precision loss)

**Comment by amandasaurus** [comment]
The `geo` crate has a [`MapCoords`](https://docs.rs/geo/0.14.2/geo/algorithm/map_coords/index.html) trait (which I added! 🙂), so you can "map" one geo object to another. I haven't tested this, but wouldn't it then to be easy to do your goal by reading a `Geometry<f64>`, and then `let geom: Geometry<T> = wkb_to_geom(...).map_coords(&|&(x, y)| (x.into(), y.into()))`?

If so, then I would like to keep this crate returning `Geometry<f64>`, because that's what the format is, and I don't want to mislead developers into thinking the format can support other types.

*(I am investigating `From<Geometry<T>> for Geometry<U: From<T>>`, which would make it even more ergonomic)*

**Comment by shuternay** [comment]
That's a nice trait, I didn't know about it, thanks! It seems to solve my problem, so I will close this PR.

Having `From<Geometry<T>>` for `Geometry<U: From<T>>` also looks nice, but in my case it wouldn't allow converting `Geometry<f64>` to `Geometry<f32>`

**Pull request closed without merging**
